[package]
name = "pack-zip"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zip = { version = "5.1.1", default-features = false, features = ["deflate"] }
pack-common = { path = "../pack-common" }
