[package]
name = "pack-common"
version = "0.1.0"
edition = "2021"

[dependencies]
deku = "0.19.1"
xml = "1.0.1"
zip = { version = "5.1.1", default-features = false, features = ["deflate"] }
pem = "3.0.5"
rsa = "0.9.8"
rasn = "0.27.2"
